--[[
Addon: DarkShift UI
Module: Custom Skins
Developed by: ©Devrak 2k19
]]--


DSC_SKINS_LIST["Simple"] =
{
	["SkinName"] = "Simple",
	["EditBgTx"] = "Simple",
	["EditBgTs"] = {
		["Simple"] = {
			["txl"] = "Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_editbg_bgl.blp",
			["txm"] = "Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_editbg_bgm.blp",
			["txr"] = "Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_editbg_bgr.blp",
			["txw"] = 24,
			["txh"] = 22,
			["lpd"] = 8,
			["rpd"] = 8,
			["ins"] = 9,
			["foc"] = false,
			["pdt"] = 3,
			["pdb"] = 5.5,
			["dmh"] = 22
		},
		["None"] = {
			["txw"] = 0,
			["txh"] = 0,
			["lpd"] = 8,
			["rpd"] = 8,
			["ins"] = 9,
			["foc"] = false,
			["pdt"] = 3,
			["pdb"] = 5.5,
			["dmh"] = 22
		},
		["Color"] = {
			["txl"] = "Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_editbgc_bgl.blp",
			["txm"] = "Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_editbgc_bgm.blp",
			["txr"] = "Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_editbgc_bgr.blp",
			["col"] = {r = 0, g = 0, b = 0, a = 0.5},
			["txw"] = 24,
			["txh"] = 22,
			["lpd"] = 8,
			["rpd"] = 8,
			["ins"] = 9,
			["foc"] = false,
			["pdt"] = 3,
			["pdb"] = 5.5,
			["dmh"] = 22
		}
	},
	["EditPosx"] = "BOTTOM",
	["EditFont"] = "Fonts\\ARIALN.TTF",
	["EditSize"] = 14,
	["EditShad"] = 0.5,
	["EditPdLn"] = 24,
	["TabDockP"] = "TOP",
	["TabHighL"] = "Interface\\ChatFrame\\ChatFrameTab-NewMessage",
	["TabBgsTx"] = "None",
	["TabBgsTs"] = {
		["None"] = {
			["txl"]="Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_transparent.tga",
			["txm"]="Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_transparent.tga",
			["txr"]="Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_transparent.tga",
			["txs"]="Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_transparent.tga"
		},
		["Color"] = {r = 0, g = 0, b = 0,a = 0.5}
	},
	["TabFoFam"] = "Interface\\AddOns\\DarkShift\\lib\\fonts\\Oswald.ttf",
	["TabFoCol"] = {r = 0, g = 0, b = 0, a = 1},
	["TabFoSiz"] = 11,
	["TabFoShd"] = 0,
	["TabDPadT"] = 0,
	["TabDPadR"] = 0,
	["TabDPadL"] = 0,
	["TabDPadB"] = 0,
	["TabSvpad"] = 0,
	["TabScrol"] = true,
	["TabAlph1"] = 0.5,
	["TabAlph2"] = 0.75,
	["TabAlcol"] = {r = 0, g = 0, b = 0},
	["ChatBtns"] = false,
	["ChatFont"] = "Fonts\\ARIALN.TTF",
	["ChatSize"] = 12,
	["ChatShad"] = 0.5,
	["ChatBgTx"] = "Simple",
	["ChatBgTs"] = {
		["Simple"] = {
			["tlb"]="Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_chatbg_tlb.blp",
			["tls"]=24,
			["tlh"]=0,
			["tlv"]=0,
			["tmb"]="Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_chatbg_ttb.blp",
			["tms"]=24,
			["tmh"]=0,
			["tmv"]=0,
			["trb"]="Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_chatbg_trb.blp",
			["trs"]=24,
			["trh"]=0,
			["trv"]=0,
			["lbb"]="Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_chatbg_lbb.blp",
			["lbs"]=24,
			["lbh"]=0,
			["lbv"]=0,
			["rbb"]="Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_chatbg_rbb.blp",
			["rbs"]=24,
			["rbh"]=0,
			["rbv"]=0,
			["blb"]="Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_chatbg_blb.blp",
			["bls"]=24,
			["blh"]=0,
			["blv"]=0,
			["brb"]="Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_chatbg_brb.blp",
			["brs"]=24,
			["brh"]=0,
			["brv"]=0,
			["bmb"]="Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_chatbg_btb.blp",
			["bms"]=24,
			["bmh"]=0,
			["bmv"]=0,
			["bgg"]="Interface\\AddOns\\DarkShift_Chat\\skins\\simple\\s_chatbg_bgg.blp",
			["bgH"]=-8,
			["bgV"]=6,
			["bgh"]=8,
			["bgv"]=-8,
			["clh"]=-15,
			["clv"]=15
		},
		["Color"] = {
			["tlb"]="",
			["tls"]=24,
			["tlh"]=0,
			["tlv"]=0,
			["tmb"]="",
			["tms"]=24,
			["tmh"]=0,
			["tmv"]=0,
			["trb"]="",
			["trs"]=24,
			["trh"]=0,
			["trv"]=0,
			["lbb"]="",
			["lbs"]=24,
			["lbh"]=0,
			["lbv"]=0,
			["rbb"]="",
			["rbs"]=24,
			["rbh"]=0,
			["rbv"]=0,
			["blb"]="",
			["bls"]=24,
			["blh"]=0,
			["blv"]=0,
			["brb"]="",
			["brs"]=24,
			["brh"]=0,
			["brv"]=0,
			["bmb"]="",
			["bms"]=24,
			["bmh"]=0,
			["bmv"]=0,
			["bgg"]="Interface\\ChatFrame\\ChatFrameBackground",
			["bgH"]=-8,
			["bgV"]=6,
			["bgh"]=8,
			["bgv"]=-8,
			["clh"]=-15,
			["clv"]=15
		},
		["None"] = {
			["bgH"]=-2,
			["bgV"]=2,
			["bgh"]=3,
			["bgv"]=-6,
			["clh"]=-2,
			["clv"]=2
		}
	},
	["ChatBgCh"] = {
		[1] = "Simple",
		[2] = "Simple",
		[3] = "Simple",
		[4] = "Simple",
		[5] = "Simple",
		[6] = "Simple",
		[7] = "Simple",
		[8] = "Simple",
		[9] = "Simple",
		[10] = "Simple"
	},
	["ChatBase"] = 1,
	["EmojiPix"] = 41,
	["TimeStmp"] = "Not",
	["TimeColo"] = "ffffff",
	["SelfColo"] = "ace5ee",
	["HlinColo"] = "7a9ae2",
	["GinvColo"] = "ffff00"
}